### ISSUE TITLE
Object Serialization trhows: Caused by: java.io.NotSerializableException

### ISSUE THREAD

**Issue by cchavez** [twitter/util#152]
Hi All.

I'm compiling some dynamic class using com.twitter.util.Eval. There is some required and I need to serialize the object created from this dynamic compiled class, I'm using org.apache.commons.lang3.SerializationUtils, when I try to serialize the object it throws:

Exception in thread "main" org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: Evaluator__84fd9b607486ff1cfa526947539e7c525a7dec04_806519483
        at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:156)
        at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:178)
        at com.livehealthier.storm.segmentation.SegmentationEngineTopology.main(SegmentationEngineTopology.java:66)
Caused by: java.io.NotSerializableException: Evaluator__84fd9b607486ff1cfa526947539e7c525a7dec04_806519483

The object should be deployed on some storm bolt, but I got this error.

anyone has tried to serialize the object created from the dynamic compiled class?

**Comment by kevinoliver** [comment]
Not answering your question directly and I don't know how good a job we've done of communicating this, but we are trying to EOL util-eval.

**Comment by cchavez** [comment]
So, is going to be a replacement for that?

**Comment by kevinoliver** [comment]
No plans for a replacement.

**Comment by mosesn** [comment]
I'm closing this since we're trying to end of life `util-eval`.  If this is still a problem for you, please let us know!
