### ISSUE TITLE
X509TrustManagerFactoryTest failing in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#196]
at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1805/consoleFull we see:

```
[twitter-util] [error] Failed tests:
[twitter-util] [error] 	com.twitter.util.security.X509TrustManagerFactoryTest
```

details:

```
[twitter-util] [info] X509TrustManagerFactoryTest:
[twitter-util] [info] - Certificate file is bogus
[twitter-util] [info] - Single certificate in collection file *** FAILED ***
[twitter-util] [info]   sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260)
[twitter-util] [info]   at sun.security.validator.Validator.validate(Validator.java:260)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
[twitter-util] [info]   at com.twitter.util.security.X509TrustManagerFactoryTest.assertTrustsCertificates(X509TrustManagerFactoryTest.scala:26)
[twitter-util] [info]   at com.twitter.util.security.X509TrustManagerFactoryTest.$anonfun$new$2(X509TrustManagerFactoryTest.scala:51)
[twitter-util] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[twitter-util] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[twitter-util] [info]   ...
[twitter-util] [info]   Cause: java.security.cert.CertPathValidatorException: timestamp check failed
[twitter-util] [info]   at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
[twitter-util] [info]   at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260)
[twitter-util] [info]   at sun.security.validator.Validator.validate(Validator.java:260)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[twitter-util] [info]   ...
[twitter-util] [info]   Cause: java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 15 00:36:17 UTC 2017
[twitter-util] [info]   at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
[twitter-util] [info]   at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
[twitter-util] [info]   at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:190)
[twitter-util] [info]   at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
[twitter-util] [info]   at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347)
[twitter-util] [info]   ...
[twitter-util] [info] - Multiple certificates in collection file *** FAILED ***
[twitter-util] [info]   sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260)
[twitter-util] [info]   at sun.security.validator.Validator.validate(Validator.java:260)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
[twitter-util] [info]   at com.twitter.util.security.X509TrustManagerFactoryTest.assertTrustsCertificates(X509TrustManagerFactoryTest.scala:26)
[twitter-util] [info]   at com.twitter.util.security.X509TrustManagerFactoryTest.$anonfun$new$3(X509TrustManagerFactoryTest.scala:66)
[twitter-util] [info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[twitter-util] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[twitter-util] [info]   ...
[twitter-util] [info]   Cause: java.security.cert.CertPathValidatorException: timestamp check failed
[twitter-util] [info]   at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
[twitter-util] [info]   at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260)
[twitter-util] [info]   at sun.security.validator.Validator.validate(Validator.java:260)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[twitter-util] [info]   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[twitter-util] [info]   ...
[twitter-util] [info]   Cause: java.security.cert.CertificateExpiredException: NotAfter: Tue Aug 15 00:36:17 UTC 2017
[twitter-util] [info]   at sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
[twitter-util] [info]   at sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:629)
[twitter-util] [info]   at sun.security.provider.certpath.BasicChecker.verifyTimestamp(BasicChecker.java:190)
[twitter-util] [info]   at sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:219)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
[twitter-util] [info]   at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
[twitter-util] [info]   at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292)
[twitter-util] [info]   at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347)
[twitter-util] [info]   ...
```

**Comment by kevinoliver** [comment]
thanks for the report. it also failed in travis ci and our internal ci. apologies for the break.

**Comment by ryanoneill** [comment]
Thanks @SethTisue. It appears that the certificates that we generated to test this code have since expired. I will generate some new ones that don't expire for 10 years so that this doesn't happen again.

**Comment by ryanoneill** [comment]
This should be fixed now.

**Comment by SethTisue** [comment]
https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1807/consoleFull:

```
[info] Project twitter-util------------: SUCCESS (project rebuilt ok)
```

thanks!
