### ISSUE TITLE
LoggersCompilationTest failing

### ISSUE THREAD

**Issue by SethTisue** [twitter/util#223]
after recent commits on the `develop` branch here, `util-slf4j-api/test:test` started failing:

```
[info] - Logging#usable after serialization with class
[debug] Test run started
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply1 started
[error] Test com.twitter.util.logging.LoggersCompilationTest.testApply1 failed: org.junit.ComparisonFailure: expected:<[com.twitter.util.logging.LoggersCompilationTest]> but was:<[NOP]>, took 0.004 sec
[error]     at com.twitter.util.logging.LoggersCompilationTest.testApply1(LoggersCompilationTest.java:17)
[error]     ...
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply1 finished, took 0.006 sec
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply2 started
[error] Test com.twitter.util.logging.LoggersCompilationTest.testApply2 failed: org.junit.ComparisonFailure: expected:<[com.twitter.util.logging.LoggersCompilationTest]> but was:<[NOP]>, took 0.001 sec
[error]     at com.twitter.util.logging.LoggersCompilationTest.testApply2(LoggersCompilationTest.java:29)
[error]     ...
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply2 finished, took 0.001 sec
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply3 started
[error] Test com.twitter.util.logging.LoggersCompilationTest.testApply3 failed: org.junit.ComparisonFailure: expected:<[LoggersCompilationTest]> but was:<[NOP]>, took 0.0 sec
[error]     at com.twitter.util.logging.LoggersCompilationTest.testApply3(LoggersCompilationTest.java:41)
[error]     ...
[debug] Test com.twitter.util.logging.LoggersCompilationTest.testApply3 finished, took 0.0 sec
[debug] Test run finished: 3 failed, 0 ignored, 3 total, 0.012s
```

this came up in the Scala community build (https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3383/consoleFull), but the problem is also reproducible just by cloning this repo and running the test

in the community build, it's on Linux, but when it's failing for me locally, that's on MacOS

not sure why this might not have been caught by your own CI...?

**Comment by dschobel** [comment]
thanks for the headsup @SethTisue , looks like it was https://github.com/twitter/util/commit/56569b9f4226b65b32d4e3f0079515b6d5542816

we'll get it fixed up.

**Comment by dschobel** [comment]
https://github.com/twitter/util/commit/7ab48ec47ae292b88fec4cb9ce67f38c6a27ec59 looks like it did the trick https://travis-ci.org/twitter/util/builds/421670890

thanks again for the report.
