### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by lssilva** [twitter/util#244]
I am using version 19.3.0 and I see in the logs the following error:

 `java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.twitter.jvm.Hotspot$.gcFromNotificationInfo(Hotspot.scala:260)
	at com.twitter.jvm.Hotspot$$anon$1.handleNotification(Hotspot.scala:95)
	at sun.management.NotificationEmitterSupport.sendNotification(NotificationEmitterSupport.java:156)
	at sun.management.GarbageCollectorImpl.createGCNotification(GarbageCollectorImpl.java:143)`

Is this a JVM conflict?

**Comment by lssilva** [comment]
Seems it was fixed on this commit: https://github.com/twitter/util/commit/52d49ad98c3ec3b08218a60d6ede322c0f7edc5e#diff-17875bdf59a97a432ccfe4dd7e877be1 
So I will close this

**Comment by kevinoliver** [comment]
Apologies for this. The good news is that it is "harmless" and your application will be unaffected. Only Finagle's tracing is using it though would break custom usages.
