### ISSUE TITLE
java.lang.UnsupportedOperationException: Position.line

### ISSUE THREAD

**Issue by cacoco** [twitter/util#60]
In trying to eval a config file that has an error in it I've seen that Eval.scala throws an UnsupportedOperationException.

```scala
FATAL: Error in config file: ../config.scala
java.lang.UnsupportedOperationException: Position.line
        at scala.reflect.internal.util.Position.line(Position.scala:205)
        at com.twitter.util.Eval$StringCompiler$$anon$1.display(Eval.scala:444)
        at scala.tools.nsc.reporters.AbstractReporter.info0(AbstractReporter.scala:49)
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply$mcV$sp(Reporter.scala:70)
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
        at scala.tools.nsc.reporters.Reporter$$anonfun$error$1.apply(Reporter.scala:70)
        at scala.tools.nsc.reporters.Reporter.withoutTruncating(Reporter.scala:42)
        at scala.tools.nsc.reporters.Reporter.error(Reporter.scala:70)
        at scala.tools.nsc.Global.globalError(Global.scala:228)
        at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1556)
        at scala.tools.nsc.Global$Run.compileSources(Global.scala:1544)
        at com.twitter.util.Eval$StringCompiler.apply(Eval.scala:530)
        at com.twitter.util.Eval$StringCompiler$$anonfun$apply$2.apply(Eval.scala:544)
        at com.twitter.util.Eval$StringCompiler$$anonfun$apply$2.apply(Eval.scala:543)
        at scala.Option.getOrElse(Option.scala:120)
        at com.twitter.util.Eval$StringCompiler.apply(Eval.scala:543)
        at com.twitter.util.Eval.applyProcessed(Eval.scala:196)
        at com.twitter.util.Eval.apply(Eval.scala:167)
        at com.twitter.ostrich.admin.RuntimeEnvironment.loadConfig(RuntimeEnvironment.scala:230)
        at com.twitter.ostrich.admin.RuntimeEnvironment.loadRuntimeConfig(RuntimeEnvironment.scala:256)
        at io.angstrom.hiveworker.Main$.main(Main.scala:11)
        at io.angstrom.hiveworker.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
        at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
```

As you can see this happens on line 444 in Eval.scala. On that line, Eval.scala is calling scala.reflect.internal.util.Position.line. Looking at the source for Position.line, it is explicitly not implemented:

```scala
def line: Int = throw new UnsupportedOperationException("Position.line")
```

Along with Position.column:

```scala
def column: Int = throw new UnsupportedOperationException("Position.column")
```
which is also used in Eval.scala on line 447.

This is preventing me from figuring out the real reason the config file evaluation is failing as the UnsuportedOperationException happens in the building of the error message to return. In order to move forward, I rebuilt util-eval replacing the call to 

```scala
messages += (severityName + "line " + (pos.line - lineOffset) + ": " + message) ::
````

with

```scala
messages += (severityName + "line " + (0 - lineOffset) + ": " + message) ::
```

which works in giving me the underlying error. So it seems to be an issue that Eval.scala is calling Position.line (and Position.column).

I am using version **6.1.0** of com.twitter:util-eval_2.10 (pulled in by com.twitter:finagle-ostrich4_2.10:6.2.1) but I've verified that the same thing happens in version **6.2.4** of com.twitter:util-eval_2.10.

```
[INFO] +- com.twitter:finagle-ostrich4_2.10:jar:6.2.1:compile
[INFO] |  \- com.twitter:ostrich_2.10:jar:9.1.0:compile
[INFO] |     +- com.twitter:util-eval_2.10:jar:6.1.0:compile
[INFO] |     |  \- org.scala-lang:scala-compiler:jar:2.10.0:compile
[INFO] |     \- com.twitter:scala-json_2.10:jar:3.0.1:compile
```

**Comment by vkostyukov** [comment]
@cacoco is it still a problem for you? Perhaps we can close this already. I'm not sure we are ever going to improve/bug-fix `util-eval` since it's nearly deprecated.

**Comment by cacoco** [comment]
@vkostyukov we can close this -- I worked around the issue then and like you said, it's basically deprecated at this point.
