### ISSUE TITLE
SyslogFormatter doesn't handle multiline messages well

### ISSUE THREAD

**Issue by plainlystated** [twitter/util#82]
The SyslogFormatter overrides lineterminator (to be ""), which means logs go to syslog as a single line. However, each sub-line (what would be a line in the default logger) still gets the priority & timestamp prefix, which makes for a very unreadable line.

For instance, here's my config:
```
new SyslogHandlerConfig {
  formatter = new SyslogFormatterConfig{
    serverName = "myserver"
  }
}
```

The following lines look fine:
```
Jan 22 19:43:35 app01.sea01.staging.abc [myserver] admin: Admin HTTP interface started on port 9900.
Jan 22 19:43:35 app01.sea01.staging.abc [myserver] http: Starting service
```

However, a stacktrace looks pretty bad (notice that the "&lt;11&gt;timestamp host..." prefix is repeated several times):
```
Jan 22 19:45:01 app01.sea01.staging.abc [myserver] stats: Error occurred recording stats<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats: com.abc.app.managers.DatabaseNotFoundException: Database with key 99229cd4e78a98357107814cc60 does not exist<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at com.abc.app.managers.DatabaseManager$$anonfun$getByKey$1.apply(DatabaseManager.scala:48)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at com.abc.app.managers.DatabaseManager$$anonfun$getByKey$1.apply(DatabaseManager.scala:44)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at com.twitter.util.Try$.apply(Try.scala:13)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at com.twitter.util.ExecutorServiceFuturePool$$anon$2.run(FuturePool.scala:75)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.util.concurrent.FutureTask.run(FutureTask.java:166)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at java.lang.Thread.run(Thread.java:701)<11>2014-01-22T19:45:01 app01.sea01.staging.abc [myserver] stats:     at com.abc.util.concurrent.ErrorLoggedThread.run(NamedThreadFactory.scala:25)
```

EDIT - code blocks to show &lt;11&gt;'s and spacing

**Comment by mosesn** [comment]
@plainlystated I don't think we have made progress on either of these in over two years (!) so my guess is that this is no longer a problem for you.  I'm going to close this for now, but if someone has other feels about SyslogFormatter, please feel free to reopen!
